export const PATHS = {
    ROOT: "/",
    HOME: "/",
    LOGIN: "/login",
    REGISTER: "/register",
    FORGOT_PASSWORD: "/forgot-password",
    RESET_PASSWORD: "/reset-password",
    DASHBOARD: "/dashboard",
    ASSETS: "/portfolio",
    TRANSACTIONS: "/transactions",
    CALCULATOR: "/calculator",
    PROFILE: "/profile",
    MARKET: "/market",
    NOT_FOUND: "*",
} as const;
